import type { NextPage } from 'next';
import Head from 'next/head';

import { Header, Icons, Promo, Block } from 'components';

const Home: NextPage = () => {
  return (
    <div className="home">
      <Head>
        <title>Brella</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {/* <Example
          text="Example Component"
          component={<Icons.ArrowIcon />}
          num={100}
          bool={true}
          arr={[{ num: 0 }, { num: 1 }, { num: 2 }]}
        /> */}
        <Header
          component={<Icons.LogoIcon />}
          arr={[
            { text: 'Our Plan', id: 1 },
            { text: 'Employers', id: 2 },
            { text: 'Brokers', id: 3 },
            { text: 'Members', id: 4 },
            { text: 'About', id: 5 },
            { text: 'Blog', id: 6 },
          ]}
        />
        <Promo />
        <section className="advantages">
          <div className="container">
            <Block
              title={`Why Brella?`}
              subtitle={`Today, any health insurance deductible can feel like a high deductible.`}
              buttonText={'See our plan'}
              text={`Brella's supplemental health plan enhances your health benefit strategy to ensure that health hardships don't become financial burdens.`}
            />
            <picture>
              <img src="/images/insurance-frame.png" alt="insurance" />
            </picture>
          </div>
        </section>
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
