import type { NextPage } from 'next';
import Head from 'next/head';

import {
  Header,
  Icons,
  Promo,
  Block,
  Brings,
  About,
  Companies,
  News,
  Contact,
  Footer,
} from 'components';

const Home: NextPage = () => {
  return (
    <div className="home">
      <Head>
        <title>Brella</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"
        />
      </Head>

      <main>
        {/* <Example
          text="Example Component"
          component={<Icons.ArrowIcon />}
          num={100}
          bool={true}
          arr={[{ num: 0 }, { num: 1 }, { num: 2 }]}
        /> */}
        <Header
          component={<Icons.LogoIcon color={'#214E41'} />}
          arr={[
            { text: 'Our Plan', id: 1 },
            { text: 'Employers', id: 2 },
            { text: 'Brokers', id: 3 },
            { text: 'Members', id: 4 },
            { text: 'About', id: 5 },
            { text: 'Blog', id: 6 },
          ]}
        />

        <Promo />

        <section className="advantages">
          <div className="container">
            <Block
              title={`Why Brella?`}
              subtitle={`Today, any health insurance deductible can feel like a high deductible.`}
              buttonText={'See our plan'}
              text={`Brella's supplemental health plan enhances your health benefit strategy to ensure that health hardships don't become financial burdens.`}
              url={'/images/insurance-frame.png'}
            />
          </div>
        </section>

        <section className="brings">
          <div className="container">
            <Brings
              title={'brella brings'}
              bringsArray={[
                {
                  title: 'Customizable benefits',
                  text: [
                    'Every Brella plan comes with a benefit for Moderate, Severe, and Catastrophic conditions. Employees can select the payout amounts that fit their needs and their budget.',
                    'Employers can fund part or all of the premiums—or offer Brella as a voluntary benefit. The choice is up to you.',
                  ],
                },
                {
                  title: 'Paperless install & admin',
                  text: [
                    `Brella's supplemental health plan enhances your health benefit strategy to ensure that health hardships don't become financial burdens.`,
                    `Brella's supplemental health plan enhances your health benefit strategy to ensure that health hardships don't become financial burdens.`,
                  ],
                },
                {
                  title: 'Effortless enrollment',
                  text: [
                    `Our broad supplemental coverage gets rid of the guesswork and puts cash in your team’s pockets for most conditions that require urgent medical attention.`,
                    `Our broad supplemental coverage gets rid of the guesswork and puts cash in your team’s pockets for most conditions that require urgent medical attention.`,
                  ],
                },
                {
                  title: 'Easy claims experience',
                  text: [
                    `Your team can’t wait for peace of mind. Brella pays on diagnosis, so members can file a claim sooner and get paid faster via our Member Portal or mobile app.`,
                    `Your team can’t wait for peace of mind. Brella pays on diagnosis, so members can file a claim sooner and get paid faster via our Member Portal or mobile app.`,
                  ],
                },
                {
                  title: 'Fast benefit payouts',
                  text: [
                    `Brella brings 100% paperless implementation, enrollment, and admin. Plug into our platforms or we’ll plug into yours.`,
                    `Brella brings 100% paperless implementation, enrollment, and admin. Plug into our platforms or we’ll plug into yours.`,
                  ],
                },
                {
                  title: 'Concierge support',
                  text: [
                    `Employers can fund part or all of the premiums—or offer Brella as a voluntary benefit. The choice is up to you.`,
                    `Brella's supplemental health plan enhances your health benefit strategy to ensure that health hardships don't become financial burdens.`,
                  ],
                },
              ]}
            />
          </div>
        </section>

        <section className="about">
          <div className="container">
            <About
              blockProps={{
                title: 'one plan, more coverage',
                subtitle:
                  'No one can predict which health issues might come their way.',
                text: `Our broad supplemental coverage gets rid of the guesswork and puts cash in your team’s pockets for most conditions that require urgent medical attention.`,
                url: '/images/about.png',
              }}
              aboutProps={{
                arr: [
                  {
                    title: '5K',
                    text: 'covered injuries and illnesses from fractures and appendicitis to cancer',
                    id: 1,
                  },
                  {
                    title: '1X',
                    text: 'more covered conditions than Accident and Critical Illness plans—combined',
                    id: 2,
                  },
                  {
                    title: '40%',
                    text: 'plans are 100% guaranteed issue. No medical underwriting required',
                    id: 3,
                  },
                  {
                    title: '0',
                    text: 'Zero limitations or exclusions for pre-existing conditions',
                    id: 4,
                  },
                ],
              }}
            />
          </div>
        </section>

        <section className="mobile">
          <div className="container">
            <Block
              title={'a better claims experience'}
              subtitle={`Give your people a plan that pays in hours—not weeks.`}
              buttonText={'Play Video'}
              text={`Your team can’t wait for peace of mind. Brella pays on diagnosis, so members can file a claim sooner and get paid faster via our Member Portal or mobile app.`}
              url={'/images/mobile-app.png'}
            />
          </div>
        </section>

        <section className="employers">
          <div className="container">
            <Block
              title={'for employers'}
              subtitle={`Easy enrollment meets simple administration.`}
              buttonText={'Learn more'}
              text={
                'Brella brings 100% paperless implementation, enrollment, and admin. Plug into our platforms or we’ll plug into yours.'
              }
              url={'/images/mobile-app.png'}
            />
          </div>
        </section>

        <section className="companies">
          <div className="container">
            <Companies
              arr={[
                { name: 'brewer lane', url: '/images/brewer-lane.png', id: 1 },
                { name: 'two sigma', url: '/images/two-sigma.png', id: 2 },
                { name: 'digitals', url: '/images/digitals.png', id: 3 },
                { name: 'founder', url: '/images/founder.png', id: 4 },
                { name: 'symphony', url: '/images/symphony.png', id: 5 },
                { name: 'two sigma', url: '/images/two-sigma.png', id: 6 },
                { name: 'digitals', url: '/images/digitals.png', id: 7 },
              ]}
            />
          </div>
          <span className="line"></span>
        </section>

        <section className="news">
          <div className="container">
            <News
              arr={[
                {
                  url: '/images/podcast.jpg',
                  title: 'Podcast',
                  subtitle:
                    'Better Voluntary Benefits with NFP Voluntary Benefits Practice Leader, Kim Heald',
                  id: 1,
                },
                {
                  url: 'images/insurance.jpg',
                  title: 'Insurance Innovation',
                  subtitle: 'How to Design Simpler Insurance Benefits',
                  id: 2,
                },
                {
                  url: 'images/benefits.jpg',
                  title: 'Benefits Strategy',
                  subtitle: 'Executive Benefits Outlook with Dan Aceti',
                  id: 3,
                },
              ]}
            />
          </div>
        </section>

        <section className="contact">
          <div className="container">
            <Contact />
          </div>
        </section>
      </main>

      <footer className="footer">
        <div className="container">
          <Footer
            logoComponent={<Icons.LogoIcon color={'#fff'} />}
            footerLinksJoin={{
              title: 'Join Brella',
              arr: [
                {
                  name: 'Our Plan',
                  id: 1,
                },
                {
                  name: 'Employers',
                  id: 2,
                },
                {
                  name: 'Brokers',
                  id: 3,
                },
                {
                  name: 'Members',
                  id: 4,
                },
              ],
            }}
            footerLinksCompany={{
              title: 'Company',
              arr: [
                {
                  name: 'About',
                  id: 1,
                },
                {
                  name: 'Blog',
                  id: 2,
                },
                {
                  name: 'Careers',
                  id: 3,
                },
                {
                  name: 'Contact',
                  id: 4,
                },
              ],
            }}
            footerSocialProps={{
              arr: [
                { component: <Icons.Linkedin />, id: 1 },
                { component: <Icons.Twitter />, id: 2 },
                { component: <Icons.Youtube />, id: 3 },
              ],
            }}
            footerContactTitle={'Get the latest'}
            footerContactsText={
              'Sign up to receive benefits news and insights in your inbox once a month.'
            }
            footerContactsArrow={<Icons.RightButton />}
            policyText={
              'Brella is a limited benefit policy; it is not a substitute for health insurance. The information provided on this website is illustrative only. A complete description of benefits, limitations, and exclusions are provided in your certificate of Insurance and applicable Riders. For a summary of limitations and exclusions, see our FAQ. Payout values listed do not guarantee an amount to be paid for listed conditions. Product not available in all states. All coverage is subject to the terms and conditions of the master group policy.'
            }
            underwrittenText={
              'Brella is underwritten by Greenhouse Life Insurance Company (NAIC 80055). Form No. PFSB11-TX'
            }
            address={
              'Reach us by mail at 2093 Philadelphia Pike #2496, Claymont, DE 19703 and by phone at'
            }
            phoneNumber={'(844) 987-1070'}
          />
        </div>
      </footer>
    </div>
  );
};

export default Home;
